services:
  db:
    image: mysql:8.0
    container_name: uds-db
    restart: always
    environment:
      MYSQL_DATABASE: gedDocumentos
      MYSQL_ROOT_PASSWORD: "root@1234"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uds-backend
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gedDocumentos?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root@1234
      - JWT_SECRET=suachavesecretasuperforte123
    volumes:
      - ./uploads:/app/uploads # Pasta para persistir os arquivos físicos

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: uds-frontend
    ports:
      - "4200:80" # Mapeia a porta 80 do Nginx para a 4200 do seu PC
    depends_on:
      - backend

volumes:
  mysql_data:
